### ISSUE TITLE
Live Install of ParrotOS requires an unzip of the rockyou.txt.gz 

### ISSUE THREAD

**Issue by AndrewJCB** [ParrotSec/linux-parrot#6]
When installing ParrotOS and attempting to use gobuster the required text file didn't exist but instead was sitting zipped in rockyou.txt.gz

The file should be unzipped upon install rather than waiting for the users to fault find upon installation especially when ParrotOS is partnered with HackTheBox!

**Comment by PalinuroSec** [comment]
you have to unpack it by yourself.
we prefer to keep it uncompressed until an user (who we suppose to be expert enough) needs it and unpacks it
